Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory",
            "name": "HttpClientFactory",
            "summary": "Factory\u0020for\u0020creating\u0020instances\u0020of\u0020ApiRequestInterface.",
            "url": "classes/Core-Factories-HttpClientFactory.html"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ClientFactory\u0020constructor",
            "url": "classes/Core-Factories-HttpClientFactory.html#method___construct"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003AgetApiRequest\u0028\u0029",
            "name": "getApiRequest",
            "summary": "Get\u0020an\u0020instance\u0020of\u0020the\u0020API\u0020request.",
            "url": "classes/Core-Factories-HttpClientFactory.html#method_getApiRequest"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003AgetHttpClient\u0028\u0029",
            "name": "getHttpClient",
            "summary": "Get\u0020an\u0020instance\u0020of\u0020the\u0020default\u0020HTTP\u0020client.",
            "url": "classes/Core-Factories-HttpClientFactory.html#method_getHttpClient"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003A\u0024uriFactory",
            "name": "uriFactory",
            "summary": "",
            "url": "classes/Core-Factories-HttpClientFactory.html#property_uriFactory"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/Core-Factories-HttpClientFactory.html#property_requestFactory"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Core-Factories-HttpClientFactory.html#property_streamFactory"
        },                {
            "fqsen": "\\Core\\Factories\\HttpClientFactory\u003A\u003A\u0024httpClient",
            "name": "httpClient",
            "summary": "",
            "url": "classes/Core-Factories-HttpClientFactory.html#property_httpClient"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory",
            "name": "ResponseConvertorFactory",
            "summary": "Factory\u0020for\u0020response\u0020converters",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#method___construct"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003AarrayConvertor\u0028\u0029",
            "name": "arrayConvertor",
            "summary": "Get\u0020ResponseInterface\u0020converter\u0020to\u0020array",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#method_arrayConvertor"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003AobjectConvertor\u0028\u0029",
            "name": "objectConvertor",
            "summary": "Get\u0020ResponseInterface\u0020converter\u0020to\u0020object",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#method_objectConvertor"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Get\u0020current\u0020ResponseInterface",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003A\u0024response",
            "name": "response",
            "summary": "PSR\u0020response",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#property_response"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorFactory\u003A\u003A\u0024convertor",
            "name": "convertor",
            "summary": "Response\u0020converter\u0020if\u0020exists",
            "url": "classes/Core-Factories-ResponseConvertorFactory.html#property_convertor"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface",
            "name": "ApiRequestInterface",
            "summary": "Interface\u0020ApiRequestInterface",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Perform\u0020a\u0020GET\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_get"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Perform\u0020a\u0020POST\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_post"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Perform\u0020a\u0020PUT\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_put"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Perform\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_delete"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Get\u0020convertor\u0020factory\u0020to\u0020easy\u0020convert\u0020to\u0020some\u0020format\nand\u0020make\u0020request",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_request"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Perform\u0020a\u0020custom\u0020request\u0020and\u0020get\u0020response.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetUri\u0028\u0029",
            "name": "setUri",
            "summary": "Set\u0020the\u0020URI\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setUri"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetUriPrefix\u0028\u0029",
            "name": "setUriPrefix",
            "summary": "Set\u0020URI\u0020prefix\u0020for\u0020all\u0020URI",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setUriPrefix"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetTimeout\u0028\u0029",
            "name": "setTimeout",
            "summary": "Set\u0020the\u0020timeout\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setTimeout"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetMaxRedirects\u0028\u0029",
            "name": "setMaxRedirects",
            "summary": "The\u0020max\u0020number\u0020of\u0020redirects\u0020to\u0020follow.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setMaxRedirects"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetFollowLocation\u0028\u0029",
            "name": "setFollowLocation",
            "summary": "Follow\u0020Location\u0020header\u0020redirects.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setFollowLocation"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "Set\u0020predefined\u0020headers\u0020for\u0020each\u0020request\nSo,\u0020each\u0020request\u0020will\u0020be\u0020send\u0020with\u0020these\u0020headers",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setHeaders"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "Set\u0020predefined\u0020header.\u0020Data\u0020will\u0020be\u0020overwriten\u0020if\u0020exists\nThis\u0020will\u0020be\u0020global\u0020header.\u0020Each\u0020request\u0020will\u0020be\u0020with\u0020this\u0020header",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setHeader"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetContentType\u0028\u0029",
            "name": "setContentType",
            "summary": "Set\u0020data\u0020format",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setContentType"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetHttpClient\u0028\u0029",
            "name": "setHttpClient",
            "summary": "Set\u0020the\u0020default\u0020HTTP\u0020client\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setHttpClient"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AgetCurrentHttpClient\u0028\u0029",
            "name": "getCurrentHttpClient",
            "summary": "Get\u0020current\u0020active\u0020HTTP\u0020client",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_getCurrentHttpClient"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetActiveHttpClient\u0028\u0029",
            "name": "setActiveHttpClient",
            "summary": "Set\u0020current\u0020active\u0020HTTP\u0020client",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setActiveHttpClient"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AaddHttpClient\u0028\u0029",
            "name": "addHttpClient",
            "summary": "Add\u0020another\u0020HTTP\u0020client\u0020and\u0020possible\u0020make\u0020it\u0020current\u0020active",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_addHttpClient"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AgetHttpClientList\u0028\u0029",
            "name": "getHttpClientList",
            "summary": "Get\u0020list\u0020of\u0020available\u0020HTTP\u0020client\u0020keys",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_getHttpClientList"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetDefaultConvertor\u0028\u0029",
            "name": "setDefaultConvertor",
            "summary": "Set\u0020default\u0020response\u0020convertor",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setDefaultConvertor"
        },                {
            "fqsen": "\\Core\\Interfaces\\ApiRequestInterface\u003A\u003AsetFakeResponse\u0028\u0029",
            "name": "setFakeResponse",
            "summary": "Set\u0020a\u0020fake\u0020response\u0020for\u0020testing\u0020purposes.",
            "url": "classes/Core-Interfaces-ApiRequestInterface.html#method_setFakeResponse"
        },                {
            "fqsen": "\\Core\\Interfaces\\HttpClientFactoryInterface",
            "name": "HttpClientFactoryInterface",
            "summary": "Main\u0020factory\u0020for\u0020creating\u0020ready\u002Dfor\u002Duse\nClientInterface\u0020and\u0020ApiRequestInterface",
            "url": "classes/Core-Interfaces-HttpClientFactoryInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\HttpClientFactoryInterface\u003A\u003AgetApiRequest\u0028\u0029",
            "name": "getApiRequest",
            "summary": "Get\u0020an\u0020instance\u0020of\u0020the\u0020API\u0020request.",
            "url": "classes/Core-Interfaces-HttpClientFactoryInterface.html#method_getApiRequest"
        },                {
            "fqsen": "\\Core\\Interfaces\\HttpClientFactoryInterface\u003A\u003AgetHttpClient\u0028\u0029",
            "name": "getHttpClient",
            "summary": "Get\u0020an\u0020instance\u0020of\u0020the\u0020default\u0020HTTP\u0020client.",
            "url": "classes/Core-Interfaces-HttpClientFactoryInterface.html#method_getHttpClient"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorFactoryInterface",
            "name": "ResponseConvertorFactoryInterface",
            "summary": "Factory\u0020for\u0020get\u0020ResponseInterface\u0020converters\u0020to\u0020different\u0020formats",
            "url": "classes/Core-Interfaces-ResponseConvertorFactoryInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorFactoryInterface\u003A\u003AarrayConvertor\u0028\u0029",
            "name": "arrayConvertor",
            "summary": "Get\u0020ResponseInterface\u0020converter\u0020to\u0020array",
            "url": "classes/Core-Interfaces-ResponseConvertorFactoryInterface.html#method_arrayConvertor"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorFactoryInterface\u003A\u003AobjectConvertor\u0028\u0029",
            "name": "objectConvertor",
            "summary": "Get\u0020ResponseInterface\u0020converter\u0020to\u0020object",
            "url": "classes/Core-Interfaces-ResponseConvertorFactoryInterface.html#method_objectConvertor"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorFactoryInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Get\u0020current\u0020ResponseInterface",
            "url": "classes/Core-Interfaces-ResponseConvertorFactoryInterface.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorInterface",
            "name": "ResponseConvertorInterface",
            "summary": "Convertor,\u0020that\u0020converts\u0020data\u0020from\u0020ResponseInterface\u0020to\u0020some\nformat,\u0020detecting\u0020by\u0020Content\u002DType\u0020header",
            "url": "classes/Core-Interfaces-ResponseConvertorInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020the\u0020converted\u0020response\u0020body.",
            "url": "classes/Core-Interfaces-ResponseConvertorInterface.html#method_get"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest",
            "name": "ApiRequest",
            "summary": "Class\u0020ApiRequest",
            "url": "classes/Core-Utils-ApiRequest.html"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ApiRequest\u0020Constructor",
            "url": "classes/Core-Utils-ApiRequest.html#method___construct"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Perform\u0020a\u0020GET\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_get"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Perform\u0020a\u0020POST\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_post"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Perform\u0020a\u0020PUT\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_put"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Perform\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_delete"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Get\u0020convertor\u0020factory\u0020to\u0020easy\u0020convert\u0020to\u0020some\u0020format\nand\u0020make\u0020request",
            "url": "classes/Core-Utils-ApiRequest.html#method_request"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Perform\u0020a\u0020custom\u0020request\u0020and\u0020get\u0020response.",
            "url": "classes/Core-Utils-ApiRequest.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetUri\u0028\u0029",
            "name": "setUri",
            "summary": "Set\u0020the\u0020URI\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setUri"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetUriPrefix\u0028\u0029",
            "name": "setUriPrefix",
            "summary": "Set\u0020URI\u0020prefix\u0020for\u0020all\u0020URI",
            "url": "classes/Core-Utils-ApiRequest.html#method_setUriPrefix"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetTimeout\u0028\u0029",
            "name": "setTimeout",
            "summary": "Set\u0020the\u0020timeout\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setTimeout"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetMaxRedirects\u0028\u0029",
            "name": "setMaxRedirects",
            "summary": "The\u0020max\u0020number\u0020of\u0020redirects\u0020to\u0020follow.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setMaxRedirects"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetFollowLocation\u0028\u0029",
            "name": "setFollowLocation",
            "summary": "Follow\u0020Location\u0020header\u0020redirects.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setFollowLocation"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "Set\u0020predefined\u0020headers\u0020for\u0020each\u0020request\nSo,\u0020each\u0020request\u0020will\u0020be\u0020send\u0020with\u0020these\u0020headers",
            "url": "classes/Core-Utils-ApiRequest.html#method_setHeaders"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "Set\u0020predefined\u0020header.\u0020Data\u0020will\u0020be\u0020overwriten\u0020if\u0020exists\nThis\u0020will\u0020be\u0020global\u0020header.\u0020Each\u0020request\u0020will\u0020be\u0020with\u0020this\u0020header",
            "url": "classes/Core-Utils-ApiRequest.html#method_setHeader"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetContentType\u0028\u0029",
            "name": "setContentType",
            "summary": "Set\u0020data\u0020format",
            "url": "classes/Core-Utils-ApiRequest.html#method_setContentType"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetHttpClient\u0028\u0029",
            "name": "setHttpClient",
            "summary": "Set\u0020the\u0020default\u0020HTTP\u0020client\u0020for\u0020the\u0020request.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setHttpClient"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AaddHttpClient\u0028\u0029",
            "name": "addHttpClient",
            "summary": "Add\u0020another\u0020HTTP\u0020client\u0020and\u0020possible\u0020make\u0020it\u0020current\u0020active",
            "url": "classes/Core-Utils-ApiRequest.html#method_addHttpClient"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetActiveHttpClient\u0028\u0029",
            "name": "setActiveHttpClient",
            "summary": "Set\u0020current\u0020active\u0020HTTP\u0020client",
            "url": "classes/Core-Utils-ApiRequest.html#method_setActiveHttpClient"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AgetHttpClientList\u0028\u0029",
            "name": "getHttpClientList",
            "summary": "Get\u0020list\u0020of\u0020available\u0020HTTP\u0020client\u0020keys",
            "url": "classes/Core-Utils-ApiRequest.html#method_getHttpClientList"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AgetCurrentHttpClient\u0028\u0029",
            "name": "getCurrentHttpClient",
            "summary": "Get\u0020current\u0020active\u0020HTTP\u0020client",
            "url": "classes/Core-Utils-ApiRequest.html#method_getCurrentHttpClient"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetDefaultConvertor\u0028\u0029",
            "name": "setDefaultConvertor",
            "summary": "Set\u0020default\u0020response\u0020convertor",
            "url": "classes/Core-Utils-ApiRequest.html#method_setDefaultConvertor"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003AsetFakeResponse\u0028\u0029",
            "name": "setFakeResponse",
            "summary": "Set\u0020a\u0020fake\u0020response\u0020for\u0020testing\u0020purposes.",
            "url": "classes/Core-Utils-ApiRequest.html#method_setFakeResponse"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024uriPrefix",
            "name": "uriPrefix",
            "summary": "Prefix\u0020for\u0020all\u0020URI",
            "url": "classes/Core-Utils-ApiRequest.html#property_uriPrefix"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024contentType",
            "name": "contentType",
            "summary": "Default\u0020content\u0020type",
            "url": "classes/Core-Utils-ApiRequest.html#property_contentType"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "Global\u0020headers",
            "url": "classes/Core-Utils-ApiRequest.html#property_headers"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024httpClients",
            "name": "httpClients",
            "summary": "List\u0020of\u0020ClientInterface\u0020objects\u0020\u0028httpClients\u0029",
            "url": "classes/Core-Utils-ApiRequest.html#property_httpClients"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024currentHttpClient",
            "name": "currentHttpClient",
            "summary": "Current\u0020key\u0020of\u0020httpClient\u0020\u0028ClientInterface\u0020object\u0029",
            "url": "classes/Core-Utils-ApiRequest.html#property_currentHttpClient"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024fakeResponse",
            "name": "fakeResponse",
            "summary": "Fake\u0020response\u0020for\u0020testing\u0020purposes",
            "url": "classes/Core-Utils-ApiRequest.html#property_fakeResponse"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024uriFactory",
            "name": "uriFactory",
            "summary": "PSR\u0020URI\u0020factory",
            "url": "classes/Core-Utils-ApiRequest.html#property_uriFactory"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "PSR\u0020Request\u0020factory",
            "url": "classes/Core-Utils-ApiRequest.html#property_requestFactory"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "PSR\u0020Uri\u0020interface",
            "url": "classes/Core-Utils-ApiRequest.html#property_uri"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "PSR\u0020stream\u0020factory",
            "url": "classes/Core-Utils-ApiRequest.html#property_streamFactory"
        },                {
            "fqsen": "\\Core\\Utils\\ApiRequest\u003A\u003A\u0024convertor",
            "name": "convertor",
            "summary": "Default\u0020response\u0020convertor",
            "url": "classes/Core-Utils-ApiRequest.html#property_convertor"
        },                {
            "fqsen": "\\Core\\Utils\\MultipartFormdataTrait",
            "name": "MultipartFormdataTrait",
            "summary": "Trait\u0020for\u0020processing\u0020multipart\/form\u002Ddata",
            "url": "classes/Core-Utils-MultipartFormdataTrait.html"
        },                {
            "fqsen": "\\Core\\Utils\\MultipartFormdataTrait\u003A\u003AbuildMultipartRequest\u0028\u0029",
            "name": "buildMultipartRequest",
            "summary": "Builds\u0020a\u0020multipart\/form\u002Ddata\u0020request\u0020with\u0020support\u0020for\u0020file\u0020uploads.",
            "url": "classes/Core-Utils-MultipartFormdataTrait.html#method_buildMultipartRequest"
        },                {
            "fqsen": "\\Core\\Utils\\MultipartFormdataTrait\u003A\u003AgetMimeType\u0028\u0029",
            "name": "getMimeType",
            "summary": "Get\u0020the\u0020MIME\u0020type\u0020of\u0020a\u0020file.",
            "url": "classes/Core-Utils-MultipartFormdataTrait.html#method_getMimeType"
        },                {
            "fqsen": "\\Core\\Utils\\MultipartFormdataTrait\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Core-Utils-MultipartFormdataTrait.html#property_streamFactory"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor",
            "name": "ResponseArrayConvertor",
            "summary": "ResponseArrayConvertor\u0020is\u0020a\u0020class\u0020that\u0020implements\u0020the\u0020ResponseConvertorInterface\nand\u0020provides\u0020methods\u0020to\u0020convert\u0020response\u0020bodies\u0020to\u0020an\u0020array\u0020format.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020ResponseArrayConvertor\u0020instance.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method___construct"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020the\u0020converted\u0020response\u0020body\u0020as\u0020an\u0020array.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method_get"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003AconvertJsonToArray\u0028\u0029",
            "name": "convertJsonToArray",
            "summary": "Convert\u0020a\u0020JSON\u0020string\u0020to\u0020an\u0020array.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method_convertJsonToArray"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003AconvertXmlToArray\u0028\u0029",
            "name": "convertXmlToArray",
            "summary": "Convert\u0020an\u0020XML\u0020string\u0020to\u0020an\u0020array.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method_convertXmlToArray"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003AnormalizeXmlToArray\u0028\u0029",
            "name": "normalizeXmlToArray",
            "summary": "Normalizes\u0020a\u0020SimpleXMLElement\u0020object\u0020to\u0020an\u0020array\u0020recursively.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method_normalizeXmlToArray"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003AconvertCsvToArray\u0028\u0029",
            "name": "convertCsvToArray",
            "summary": "Convert\u0020a\u0020CSV\u0020string\u0020to\u0020an\u0020array.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#method_convertCsvToArray"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseArrayConvertor\u003A\u003A\u0024response",
            "name": "response",
            "summary": "PSR\u0020Response",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseArrayConvertor.html#property_response"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseConverterTrait",
            "name": "ResponseConverterTrait",
            "summary": "ResponseConverterTrait\u0020provides\u0020common\u0020methods\u0020for\u0020converting\u0020response\nbodies\u0020to\u0020different\u0020formats.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseConverterTrait.html"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseConverterTrait\u003A\u003AdetectCsvDelimiter\u0028\u0029",
            "name": "detectCsvDelimiter",
            "summary": "Detects\u0020the\u0020delimiter\u0020used\u0020in\u0020a\u0020CSV\u0020file\u0020based\u0020on\u0020the\u0020given\u0020lines.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseConverterTrait.html#method_detectCsvDelimiter"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseConverterTrait\u003A\u003AformatXmlErrors\u0028\u0029",
            "name": "formatXmlErrors",
            "summary": "Format\u0020XML\u0020errors\u0020as\u0020a\u0020string.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseConverterTrait.html#method_formatXmlErrors"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseConverterTrait\u003A\u003AgetContentType\u0028\u0029",
            "name": "getContentType",
            "summary": "Safe\u0020get\u0020Content\u002DType\u0020from\u0020ResponseInterface",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseConverterTrait.html#method_getContentType"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor",
            "name": "ResponseObjectConvertor",
            "summary": "ResponseObjectConvertor\u0020is\u0020a\u0020response\u0020convertor\u0020class\u0020that\u0020converts\nresponse\u0020bodies\u0020to\u0020objects.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020ResponseObjectConvertor\u0020instance.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method___construct"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020the\u0020converted\u0020response\u0020body\u0020as\u0020an\u0020object.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method_get"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003AconvertJsonToObject\u0028\u0029",
            "name": "convertJsonToObject",
            "summary": "Convert\u0020a\u0020JSON\u0020string\u0020to\u0020an\u0020object.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method_convertJsonToObject"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003AconvertXmlToObject\u0028\u0029",
            "name": "convertXmlToObject",
            "summary": "Convert\u0020an\u0020XML\u0020string\u0020to\u0020an\u0020object.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method_convertXmlToObject"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003AnormalizeXmlToObject\u0028\u0029",
            "name": "normalizeXmlToObject",
            "summary": "Normalize\u0020a\u0020SimpleXMLElement\u0020object\u0020to\u0020an\u0020object.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method_normalizeXmlToObject"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003AconvertCsvToObject\u0028\u0029",
            "name": "convertCsvToObject",
            "summary": "Convert\u0020a\u0020CSV\u0020string\u0020to\u0020an\u0020object.",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#method_convertCsvToObject"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors\\ResponseObjectConvertor\u003A\u003A\u0024response",
            "name": "response",
            "summary": "PSR\u0020Response",
            "url": "classes/Core-Utils-ResponseConvertors-ResponseObjectConvertor.html#property_response"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData",
            "name": "ResponseConvertorData",
            "summary": "Class\u0020for\u0020get\u0020converted\u0020response\u0020data",
            "url": "classes/Core-Factories-ResponseConvertorData.html"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Factories-ResponseConvertorData.html#method___construct"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020array",
            "url": "classes/Core-Factories-ResponseConvertorData.html#method_toArray"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003AtoObject\u0028\u0029",
            "name": "toObject",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020object",
            "url": "classes/Core-Factories-ResponseConvertorData.html#method_toObject"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003AownFormat\u0028\u0029",
            "name": "ownFormat",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020own\u0020format\nfrom\u0020own\u0020implementation\u0020of\u0020ResponseConverterInterface",
            "url": "classes/Core-Factories-ResponseConvertorData.html#method_ownFormat"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Get\u0020ResponseInterface\u0020object",
            "url": "classes/Core-Factories-ResponseConvertorData.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003A\u0024response",
            "name": "response",
            "summary": "PSR\u0020response",
            "url": "classes/Core-Factories-ResponseConvertorData.html#property_response"
        },                {
            "fqsen": "\\Core\\Factories\\ResponseConvertorData\u003A\u003A\u0024convertor",
            "name": "convertor",
            "summary": "Response\u0020converter\u0020if\u0020exists",
            "url": "classes/Core-Factories-ResponseConvertorData.html#property_convertor"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorDataInterface",
            "name": "ResponseConvertorDataInterface",
            "summary": "Interface\u0020for\u0020get\u0020data\u0020from\u0020response",
            "url": "classes/Core-Interfaces-ResponseConvertorDataInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorDataInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020array",
            "url": "classes/Core-Interfaces-ResponseConvertorDataInterface.html#method_toArray"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorDataInterface\u003A\u003AtoObject\u0028\u0029",
            "name": "toObject",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020object",
            "url": "classes/Core-Interfaces-ResponseConvertorDataInterface.html#method_toObject"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorDataInterface\u003A\u003AownFormat\u0028\u0029",
            "name": "ownFormat",
            "summary": "Get\u0020ResponseInterface\u0020body\u0020converted\u0020to\u0020own\u0020format\nfrom\u0020own\u0020implementation\u0020of\u0020ResponseConverterInterface",
            "url": "classes/Core-Interfaces-ResponseConvertorDataInterface.html#method_ownFormat"
        },                {
            "fqsen": "\\Core\\Interfaces\\ResponseConvertorDataInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Get\u0020ResponseInterface\u0020object",
            "url": "classes/Core-Interfaces-ResponseConvertorDataInterface.html#method_getResponse"
        },                {
            "fqsen": "\\Core\\Exceptions\\RequestException",
            "name": "RequestException",
            "summary": "",
            "url": "classes/Core-Exceptions-RequestException.html"
        },                {
            "fqsen": "\\Core\\Exceptions\\RequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Exceptions-RequestException.html#method___construct"
        },                {
            "fqsen": "\\Core\\Exceptions\\RequestException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/Core-Exceptions-RequestException.html#method_getRequest"
        },                {
            "fqsen": "\\Core\\Exceptions\\RequestException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Core-Exceptions-RequestException.html#property_request"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/core-exceptions.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        },                {
            "fqsen": "\\Core\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/core-factories.html"
        },                {
            "fqsen": "\\Core\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-interfaces.html"
        },                {
            "fqsen": "\\Core\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "namespaces/core-utils.html"
        },                {
            "fqsen": "\\Core\\Utils\\ResponseConvertors",
            "name": "ResponseConvertors",
            "summary": "",
            "url": "namespaces/core-utils-responseconvertors.html"
        }            ]
);
